apiVersion: v1
kind: Service
metadata:
  name: go-service
  namespace: dephealth-test
  labels:
    app: go-service
spec:
  selector:
    app: go-service
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP
