apiVersion: v1
kind: Service
metadata:
  name: conformance-test-service-java
  namespace: dephealth-conformance
  labels:
    app: conformance-test-service-java
spec:
  selector:
    app: conformance-test-service-java
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP
