apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: java-service
  namespace: dephealth-test
  labels:
    app: java-service
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
  hostnames:
    - test3.kryukov.lan
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: java-service
          port: 8080
