apiVersion: v1
kind: Service
metadata:
  name: grpc-stub
  namespace: dephealth-conformance
  labels:
    app: grpc-stub
spec:
  selector:
    app: grpc-stub
  ports:
    - port: 9090
      targetPort: 9090
      name: grpc
    - port: 8080
      targetPort: 8080
      name: admin
  type: ClusterIP
