{{- if .Values.stubs.httpStub.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-stub
  namespace: {{ include "dephealth-infra.namespace" . }}
  labels:
    {{- include "dephealth-infra.labels" . | nindent 4 }}
    {{- include "dephealth-infra.selectorLabels" (dict "name" "http-stub") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "dephealth-infra.selectorLabels" (dict "name" "http-stub") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dephealth-infra.selectorLabels" (dict "name" "http-stub") | nindent 8 }}
    spec:
      containers:
        - name: http-stub
          image: {{ include "dephealth-infra.customImage" (dict "registry" .Values.global.pushRegistry "image" .Values.stubs.httpStub.image "tag" .Values.stubs.httpStub.tag) }}
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: PORT
              value: "8080"
          readinessProbe:
            httpGet:
              path: /admin/status
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /admin/status
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.stubs.httpStub.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: http-stub
  namespace: {{ include "dephealth-infra.namespace" . }}
  labels:
    {{- include "dephealth-infra.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "dephealth-infra.selectorLabels" (dict "name" "http-stub") | nindent 4 }}
  ports:
    - port: 8080
      targetPort: http
      name: http
{{- end }}
