{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ include "dephealth-infra.namespace" . }}
  labels:
    {{- include "dephealth-infra.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password | quote }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-primary
  namespace: {{ include "dephealth-infra.namespace" . }}
  labels:
    {{- include "dephealth-infra.labels" . | nindent 4 }}
    {{- include "dephealth-infra.selectorLabels" (dict "name" "postgres-primary") | nindent 4 }}
spec:
  serviceName: postgres-primary
  replicas: 1
  selector:
    matchLabels:
      {{- include "dephealth-infra.selectorLabels" (dict "name" "postgres-primary") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dephealth-infra.selectorLabels" (dict "name" "postgres-primary") | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: {{ include "dephealth-infra.image" (dict "registry" .Values.global.imageRegistry "image" .Values.postgres.image "tag" .Values.postgres.tag) }}
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.credentials.user | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: {{ .Values.postgres.credentials.database | quote }}
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", {{ .Values.postgres.credentials.user | quote }}]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", {{ .Values.postgres.credentials.user | quote }}]
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            {{- toYaml .Values.postgres.primary.resources | nindent 12 }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.global.storageClass }}
        storageClassName: {{ .Values.global.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgres.primary.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-primary
  namespace: {{ include "dephealth-infra.namespace" . }}
  labels:
    {{- include "dephealth-infra.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "dephealth-infra.selectorLabels" (dict "name" "postgres-primary") | nindent 4 }}
  ports:
    - port: 5432
      targetPort: postgres
      name: postgres
{{- end }}
