{{- if .Values.rabbitmq.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: {{ include "dephealth-infra.namespace" . }}
  labels:
    {{- include "dephealth-infra.labels" . | nindent 4 }}
    {{- include "dephealth-infra.selectorLabels" (dict "name" "rabbitmq") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "dephealth-infra.selectorLabels" (dict "name" "rabbitmq") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dephealth-infra.selectorLabels" (dict "name" "rabbitmq") | nindent 8 }}
    spec:
      containers:
        - name: rabbitmq
          image: {{ include "dephealth-infra.image" (dict "registry" .Values.global.imageRegistry "image" .Values.rabbitmq.image "tag" .Values.rabbitmq.tag) }}
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{ .Values.rabbitmq.credentials.user | quote }}
            - name: RABBITMQ_DEFAULT_PASS
              value: {{ .Values.rabbitmq.credentials.password | quote }}
          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "check_port_connectivity"]
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "status"]
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.rabbitmq.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: {{ include "dephealth-infra.namespace" . }}
  labels:
    {{- include "dephealth-infra.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "dephealth-infra.selectorLabels" (dict "name" "rabbitmq") | nindent 4 }}
  ports:
    - port: 5672
      targetPort: amqp
      name: amqp
    - port: 15672
      targetPort: management
      name: management
{{- end }}
